# Generated by Django 4.0.5 on 2022-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_historicalprojects_state_alter_projects_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='state',
            field=models.CharField(choices=[('ACT', 'Active'), ('UNACT', 'Inactive')], default='ACT', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='state',
            field=models.CharField(choices=[('ACT', 'Active'), ('UNACT', 'Inactive')], default='ACT', max_length=10),
        ),
    ]
