# Generated by Django 4.0.5 on 2022-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_alter_historicalprojects_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='status',
            field=models.CharField(default='cero', max_length=30),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default='cero', max_length=30),
        ),
    ]
