# Generated by Django 4.0.5 on 2022-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_alter_historicalprojects_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='status',
            field=models.IntegerField(choices=[('cero', 'cero'), ('uno', 'uno')], default='cero'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.IntegerField(choices=[('cero', 'cero'), ('uno', 'uno')], default='cero'),
        ),
    ]
