# Generated by Django 4.0.5 on 2022-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_alter_historicalprojects_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='Activo', max_length=10),
        ),
    ]
