# Generated by Django 4.0.5 on 2022-07-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ACT', 'Active'), ('UNACT', 'Inactive')], default='ACT', max_length=10)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name='Deletion Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Client Name ')),
                ('contract', models.IntegerField(verbose_name='Id Contract')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.CharField(choices=[('ACT', 'Active'), ('UNACT', 'Inactive')], default='ACT', max_length=10)),
                ('creation_date', models.DateField(blank=True, editable=False, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(blank=True, editable=False, verbose_name='Modification Date')),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, verbose_name='Deletion Date')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Client Name ')),
                ('contract', models.IntegerField(verbose_name='Id Contract')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Client',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
