# Generated by Django 4.0.5 on 2022-07-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('unactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('unactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
