# Generated by Django 4.0.5 on 2022-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_client_state_remove_historicalclient_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0),
        ),
    ]
