# Generated by Django 4.0.5 on 2022-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_client_status_alter_historicalclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[('cero', 'cero'), ('uno', 'uno')], default='cero', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.IntegerField(choices=[('cero', 'cero'), ('uno', 'uno')], default='cero', max_length=10),
        ),
    ]
