# Generated by Django 4.0.5 on 2022-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_client_status_alter_historicalclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default='cero', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.CharField(default='cero', max_length=30),
        ),
    ]
