# Generated by Django 4.0.5 on 2022-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_client_status_alter_historicalclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='Activo', max_length=10),
        ),
    ]
