# Generated by Django 4.0.5 on 2022-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_client_status_alter_historicalclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
